### PR TITLE
systemv.js change to allow to work with amazon AWS servers

### PR DESCRIPTION
**Pull request by JohnNelsonAPPX**

### CODE REVIEW

**Comment by tacooper** [comment]
Note that this is only required until the underlying issue #31 is fixed.

**Comment by coreybutler** [comment]
There are [already checks](https://github.com/coreybutler/node-linux/blob/master/lib/systemv.js#L19) for `amzn`. @tacooper is right though... #31 needs to be resolved. If someone submits a PR against #31, I would merge it. I just don't have time to address it personally at the moment.

**Comment by JohnNelsonAPPX** [comment]
My apologies. I actually fixed this 6 months ago, but am new to git. Was revisiting it when I saw I didn't submit the pull request to you like I thought I did, but instead of checking the new code first, I just went ahead and submitted the pull request.

**Comment by coreybutler** [comment]
No worries... I'm happy people are committing!

**Comment by tacooper** [comment]
@coreybutler I submitted a PR (#38), let me know when you get a chance to review it :)

**Comment by tacooper** [comment]
@coreybutler any idea of when you'll have time to review/merge PR #38? thanks

**Pull request closed without merging**
